#!/bin/bash

# Path to the project directory
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Default command if none provided
COMMAND=${1:-record}
shift

case "$COMMAND" in
    record)
        sudo docker-compose -f "$PROJECT_DIR/docker-compose.yml" run --rm terminal-secretary python3 main.py record "$@"
        ;;
    search)
        sudo docker-compose -f "$PROJECT_DIR/docker-compose.yml" run --rm terminal-secretary python3 main.py search "$@"
        ;;
    build)
        sudo docker-compose -f "$PROJECT_DIR/docker-compose.yml" build
        ;;
    *)
        echo "Usage: secretary {record|search|build} [query]"
        exit 1
        ;;
esac
